services:
  minecraft:
    image: itzg/minecraft-server
    tty: true # Allocate a pseudo-TTY
    container_name: minecraft-server
    ports:
      - "25565:25565"   # Change host IP as needed
    environment:
      EULA: "TRUE"                  # Accept Minecraft's EULA
      VERSION: "1.20.1"             # Change to specific version if needed
      TYPE: "FORGE"                 # Server type (e.g., VANILLA, FORGE)
      MEMORY: "12G"                 # Adjust memory as required
      OPS: "rakdcolon, goofygarlic" # Add your username as an operator
    volumes:
      - "./data:/data"              # Persistent world and server data
      - "./config:/config"          # Custom configuration files
      - "./mods:/mods"              # Mods folder for Forge/Fabric
    restart: on-failure:3

  backup:
    image: alpine
    container_name: minecraft-backup
    volumes:
      - "./backups:/project"
    restart: on-failure:3
